# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    branches:
      only:
        - master
    steps:
      - checkout
      - run: if [[ ! -e $(which rsync) ]]; then sudo apt-get install rsync fi
      - run:
          name: deploy
          command: |
            export DEPLOY_USERNAME=brand
            mkdir ~/.ssh || rm -f ~/.ssh/known_hosts
            mv ./.circleci/known_hosts ~/.ssh/
            rsync -rptgoDzL --delete cnf www ${DEPLOY_USERNAME}@nbf01.opsserver.ch:.
            ssh ${DEPLOY_USERNAME}@nbf01.opsserver.ch "sudo /usr/sbin/service nginx reload"
